<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HN0lSHt' shared service.

return $this->privates['.service_locator.HN0lSHt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'repo' => array('privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService.php', true),
));
