<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Pu8KG5q' shared service.

return $this->privates['.service_locator.Pu8KG5q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'encoder' => array('services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
    'user' => array('privates', '.errored..service_locator.Pu8KG5q.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Pu8KG5q": it references class "App\\Entity\\User" but no such service exists.'),
));
