<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rrvz0uA' shared service.

return $this->privates['.service_locator.rrvz0uA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'article' => array('privates', '.errored..service_locator.rrvz0uA.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.rrvz0uA": it references class "App\\Entity\\Articles" but no such service exists.'),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
));
