<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDGkcP8F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDGkcP8F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDGkcP8F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDGkcP8F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDGkcP8F\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'DGkcP8F',
    'container.build_id' => 'c3d2fe09',
    'container.build_time' => 1548059413,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDGkcP8F');
